services:

  postgres-keycloak:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    networks:
      - ndi-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d image_service" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    container_name: keycloak
    depends_on:
      postgres-keycloak:
        condition: service_healthy
    environment:
      KEYCLOAK_MODE: ${KEYCLOAK_MODE:-dev}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: pwd
      #KC_HOSTNAME_STRICT: false
      #KC_HOSTNAME_STRICT_BACKCHANNEL: false

      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB: postgres
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: pwd

      #Prod only
      #KC_HOSTNAME: ${KC_HOSTNAME}
      #KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      #KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
    ports:
      - "8090:8080"
    volumes:
      - ./keycloak-data:/opt/keycloak/data
    networks:
      - ndi-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "5003:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      KEYCLOAK_URL: http://keycloak:8080
      ISSUER_URI: http://keycloak:8080/auth/realms/shopifake
      KEYCLOAK_JWK_SET_URI: http://keycloak:8080/realms/shopifake/protocol/openid-connect/certs
    depends_on:
      keycloak:
        condition: service_started
    networks:
      - ndi-network
    restart: unless-stopped

volumes:
  postgres_keycloak_data:
  keycloak-data:

networks:
  ndi-network:
    name: ndi-network
    driver: bridge

